version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "PetProject"
      POSTGRES_USER: "irvanev"
      POSTGRES_PASSWORD: "6658005"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"